//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressServiceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public string driver_id { get; set; }
        public string vehicle_type_id { get; set; }
        public string license_plate { get; set; }
    
        public virtual User User { get; set; }
        public virtual VehicleType VehicleType { get; set; }
    }
}
