//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressServiceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderHistories = new HashSet<OrderHistory>();
            this.Payments = new HashSet<Payment>();
            this.Ratings = new HashSet<Rating>();
            this.Revenues = new HashSet<Revenue>();
        }
    
        public string order_id { get; set; }
        public string customer_id { get; set; }
        public string order_content { get; set; }
        public Nullable<System.DateTime> delivery_time { get; set; }
        public string delivery_address { get; set; }
        public Nullable<System.DateTime> pickup_time { get; set; }
        public string pickup_address { get; set; }
        public string vehicle_type_id { get; set; }
        public string discount_code { get; set; }
        public decimal distance { get; set; }
        public decimal total_amount { get; set; }
        public string status { get; set; }
        public string driver_id { get; set; }
        public string cancellation_reason_id { get; set; }
        public Nullable<System.DateTime> cancellation_time { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<double> DeliveryLatitude { get; set; }
        public Nullable<double> DeliveryLongitude { get; set; }
        public Nullable<double> PickupLatitude { get; set; }
        public Nullable<double> PickupLongitude { get; set; }
        public Nullable<decimal> DiscountedAmount { get; set; }
    
        public virtual CancellationReason CancellationReason { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHistory> OrderHistories { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Revenue> Revenues { get; set; }
    }
}
