//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressServiceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string rating_id { get; set; }
        public string order_id { get; set; }
        public string customer_id { get; set; }
        public string driver_id { get; set; }
        public byte rating1 { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
